# frontend/Dockerfile
FROM node:20-alpine
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .

# Expose the port and define the command
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
